# configuration file for dotnet-releaser
profile = "custom"
[msbuild]
project = "Cyber Sleuth Mod Evolution Analyzer.sln"
[github]
user = "GraionDilach"
repo = "CyberSleuthModEvolutionAnalyzer"
[nuget]
publish = false
[scoop]
publish = false
[msbuild.properties]
PublishTrimmed = false
PublishSingleFile = true
SelfContained = true
PublishReadyToRun = true 
CopyOutputSymbolsToPublishDirectory = false
SkipCopyingSymbolsToOutputDirectory = true
[[pack]]
rid = ["win-x64"]
kinds = ["zip"]
